### ISSUE TITLE
HW description

### ISSUE THREAD

**Issue by electroklas** [tekgator/esp8266-window-shutter#3]
Interesting project,
But I miss a description of the HW side.

Is the 8266 I/O  hardwired to a hacked Becker remote ?

**Comment by tekgator** [comment]
Hi @electroklas, I've added a bit more description and documentation. Unfortunately I've moved in the meantime, therefore I don't have the actual hardware in front of me anymore. Otherwise I could have posted some pictures of it as well.

**Comment by electroklas** [comment]
Gr8... fast response.. :)
Exactly what's needed... much appreciated..
